### ISSUE TITLE
Support extracted files

### ISSUE THREAD

**Issue by DeathChaos25** [HeartHeroDE/th-hack-tools#3]
With update 1.0.1 and 1.0.2, a lot of files are being read separate and layered over DATA1, making some of the edits of this tool useless as the particular data is no longer being read from DATA1, particularly character data edits, because this file was included in patch 1.0.2 to adjust Ignatz' height
(rom:/patch2/nx/data/PersonData.bin)

Adding support for separate files would both allow people who have fully extracted their DATA1 contents to use this tool as well as future proofing it for situations like this one.

**Comment by NaturalHarmonia** [comment]
I used JKSV to try and extract my save but when I try to open slot0 or slot1 I get this error saying something about data1.
